name: MultiArchDockerBuild

on:
  push:
    branches:
      - master
      - develop

jobs:
  build_multi_arch_image:
    name: Build multi-arch Docker image.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push master
        if: ${{ github.ref == 'refs/heads/master' }}
        id: docker_build_master
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            charlocharlie/epicgames-freegames:${{ github.sha }}
            charlocharlie/epicgames-freegames:latest
            ghcr.io/claabs/epicgames-freegames-node:latest
            ghcr.io/claabs/epicgames-freegames-node:${{ github.sha }}
          platforms: linux/amd64,linux/arm64,linux/arm/v6

      - name: Build and push dev
        if: ${{ github.ref == 'refs/heads/develop' }}
        id: docker_build_dev
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            charlocharlie/epicgames-freegames:dev
            ghcr.io/claabs/epicgames-freegames-node:dev
          platforms: linux/amd64,linux/arm64,linux/arm/v6

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
