name: Container Scan

on:
  schedule:
    - cron: "30 17 * * 4"
  workflow_dispatch:

jobs:
  trivy:
    runs-on: ubuntu-latest
    steps:
      - name: Create folder
        run: mkdir -p sarif-results
      - name: Scan Alpine image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ghcr.io/claabs/epicgames-freegames-node:latest
          format: sarif
          output: sarif-results/alpine.sarif
      - name: Scan Debian image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ghcr.io/claabs/epicgames-freegames-node:debian
          format: sarif
          output: sarif-results/debian.sarif
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: sarif-results